# Generated by Django 4.2.3 on 2024-02-12 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('is_child', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'fracture'), ('2', 'decay'), ('3', 'missing'), ('4', 'missing-indicated'), ('5', 'prostheses-good'), ('6', 'prostheses-bad'), ('7', 'filling-good'), ('8', 'filling-bad'), ('9', 'sealant-good'), ('10', 'sealant-bad')], max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='teeth', to='treatments.profile')),
            ],
            options={
                'verbose_name': 'Tooth',
                'verbose_name_plural': 'Teeth',
            },
        ),
    ]
